"""EVB packet definitions and payload layouts."""

PREAMBLE = 0xAA
MAX_PAYLOAD = 64

# Message types
PING = 0x01
SNAPSHOT = 0x04
DELTA = 0x05
DISTANCE = 0x07
POWER = 0x08
BUNDLE = 0x09
IMU = 0x0A
ARM_ENCODER_TARGET = 0x10
GET_ENCODER_TARGET = 0x11
WAIT_ENCODER_TARGET = 0x12
DISARM_ENCODER_TARGET = 0x13
ARM_TENSION_TRIGGER = 0x14
GET_TENSION_TRIGGER = 0x15
WAIT_TENSION_TRIGGER = 0x16
DISARM_TENSION_TRIGGER = 0x17
SAVE_ENCODERS = 0x18
ERROR = 0xE0

# Expected payload lengths
EXPECTED_LENGTHS = {
    SNAPSHOT: 11,
    DELTA: 9,
    DISTANCE: 13,
    BUNDLE: 32,
    IMU: 44,
    ARM_ENCODER_TARGET: 24,
    GET_ENCODER_TARGET: 24,
    WAIT_ENCODER_TARGET: 24,
    DISARM_ENCODER_TARGET: 24,
    ARM_TENSION_TRIGGER: 24,
    GET_TENSION_TRIGGER: 24,
    WAIT_TENSION_TRIGGER: 24,
    DISARM_TENSION_TRIGGER: 24,
    SAVE_ENCODERS: 1,
}

ERROR_CODES = {
    1: "bad length",
    2: "compact timeout",
    3: "unknown command",
    4: "no data",
    5: "compact target command failed",
}
